### ISSUE TITLE
Scenes lost all the references to scripts and shaders

### ISSUE THREAD

**Issue by cozlind** [paraself/ParticlePhysics2D-Unity#1]
Please don't ignore the .meta files when using version control.
When the project don't have both library folder and .meta files, all references broke.
[Unity Manual](https://docs.unity3d.com/Manual/BehindtheScenes.html)

**Comment by paraself** [comment]
Hi Thanks for trying out this plugin. Once I have some free time, I'll work on this. ;D

**Comment by paraself** [comment]
Commited all the .meta files.
